version: '3.4'

services:
  identityapi:
    image: identityapi:dev
    container_name: IdentityAPI
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "IdentityAPI"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_identityapi$
    volumes:
      - /Users/marcin/Desktop/Marcin/IiE/sem3/TTSAW/Proba1/Media/Media/IdentityAPI:/app
      - /Users/marcin/Desktop/Marcin/IiE/sem3/TTSAW/Proba1/Media:/src
      - /Users/marcin/vsdbg/vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_identityapi$

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_identityapi$ \"/app/bin/Debug/net7.0/IdentityAPI.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  peopleapi:
    image: peopleapi:dev
    container_name: PeopleAPI
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "PeopleAPI"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_peopleapi$
    volumes:
      - /Users/marcin/Desktop/Marcin/IiE/sem3/TTSAW/Proba1/Media/Media/PeopleAPI:/app
      - /Users/marcin/Desktop/Marcin/IiE/sem3/TTSAW/Proba1/Media:/src
      - /Users/marcin/vsdbg/vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_peopleapi$

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_peopleapi$ \"/app/bin/Debug/net7.0/PeopleAPI.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  postapi:
    image: postapi:dev
    container_name: PostAPI
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "PostAPI"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_postapi$
    volumes:
      - /Users/marcin/Desktop/Marcin/IiE/sem3/TTSAW/Proba1/Media/Media/PostAPI:/app
      - /Users/marcin/Desktop/Marcin/IiE/sem3/TTSAW/Proba1/Media:/src
      - /Users/marcin/vsdbg/vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_postapi$

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_postapi$ \"/app/bin/Debug/net7.0/PostAPI.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  webui:
    image: webui:dev
    container_name: WebUI
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "WebUI"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_webui$
    volumes:
      - /Users/marcin/Desktop/Marcin/IiE/sem3/TTSAW/Proba1/Media/Media/WebUI:/app
      - /Users/marcin/Desktop/Marcin/IiE/sem3/TTSAW/Proba1/Media:/src
      - /Users/marcin/vsdbg/vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_webui$

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_webui$ \"/app/bin/Debug/net7.0/WebUI.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
